# Site settings
title: Plataforma Indignada
email: plataformaindignada@domain.com
description: > 
 La Plataforma Indignada, es un medio por cual se busca la articulación del movimiento civico nacional de indignados en Honduras
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site



timezone: America/Tegucigalpa

# Build settings
markdown: kramdown
